name: eodie
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - shapely=1.7
  - rasterio=1.2
  - rasterstats=0.14
  - fiona=1.8
  - numpy=1.20
  - gdal=3.1.4
  - pyyaml=5.4.1
  - pytest
  - matplotlib
  - geopandas
  - timeit